### ISSUE TITLE
Add support for creating dynamic static objects

### ISSUE THREAD

**Issue by jcansdale** [ekonbenefits/dynamitey#15]
After looking at the following unit test:

```
        [Test]
        public void TestStaticDateTimeMethod()
        {
            var @static = InvokeContext.CreateStatic;
            object tDateDyn = "01/20/2009";
            var tDate = Dynamic.InvokeMember(@static(typeof(DateTime)), "Parse", tDateDyn);
            Assert.AreEqual(new DateTime(2009, 1, 20), tDate);
        }
```

I was hoping something like this might be possible:

```
            var @static = InvokeContext.CreateStatic;
            object tDateDyn = "01/20/2009";

            dynamic staticObject = @static(typeof(DateTime));
            var tDate = staticObject.Parse("Parse", tDateDyn);

            Assert.AreEqual(new DateTime(2009, 1, 20), tDate);
```

Is there some technical reason why this would be impossible?

Thanks!

**Comment by jbtule** [comment]
It should be possible but you need to omit the extra  "Parse"  arg so it looks like this:

           dynamic staticObject = @static(typeof(DateTime));
           var tDate = staticObject.Parse(tDateDyn);

**Comment by jbtule** [comment]
wait... that's incorrect...

**Comment by jbtule** [comment]
Context only flags my code to use the dlr code that targets the type. You can use a forward like `Get` from `Dynamitey.DynamicObjects` to do what you want.

```
var @static = InvokeContext.CreateStatic;
var stringDate = "01/20/2009";
dynamic dateTimeType = new Get(@static(typeof(DateTime)));
var parsedDate = dateTimeType.Parse(stringDate);
Assert.AreEqual(new DateTime(2009, 1, 20), parsedDate);
```

**Comment by jcansdale** [comment]
Thanks for the tip. That seems to work. :smile:

I've tried stepping through the code to see what it's doing, but it all seems pretty involved! I was hoping I might be able to extend DynamicObject and somehow use the default C# binding code to target static methods.
