### ISSUE TITLE
Could not load file or assembly 'ImpromptuInterface, PublicKeyToken=0b1781c923b2975b'

### ISSUE THREAD

**Issue by matthiesenj** [ekonbenefits/dynamitey#17]
Hi,

I am working on a plugin assembly for a piece of third party software. My plugin references another assembly of mine which eventually references Dynamitey. Now, the other assembly works fine under other circumstances, but when used with the plugin it fails. The error is this:

```
14:58:57.545: AssemblyResolve looking for ImpromptuInterface, PublicKeyToken=0b1781c923b2975b, requesting assembly N/A
14:58:57.547: Could not resolve assembly ImpromptuInterface, PublicKeyToken=0b1781c923b2975b, trying redirect to self.
TargetInvocation exception: System.TypeInitializationException: The type initializer for 'Dynamitey.Dynamic' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'ImpromptuInterface, PublicKeyToken=0b1781c923b2975b' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044) ---> System.IO.FileLoadException: A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Dynamitey.DynamicObjects.LateType..ctor(String typeName)
   at Dynamitey.Dynamic..cctor()
   --- End of inner exception stack trace ---
   at Dynamitey.Dynamic.InvokeGet(Object target, String name)

```
So when Dynamic.InvokeGet is called, it eventually tries to load (from file?) the assembly named ImpromptuInterface, which is some sort of dynamic assembly created inside Dynamic.cs, i.e. not something that can be loaded from file. Looking at the debug output, I suspect the problem is triggered by the way the 3rd party software resolves plugin assemblies.

If I create a test project and 'statically' reference the plugin assembly, the problem does not occur.

Now, I am not claiming that this is a bug as such in Dynamitey, but maybe it could be made immune to such a problem?

**Comment by jbtule** [comment]
That's interesting.  So Dynamitey has an API for loading types at runtime if they are present and then gaining extra features, and if not, not big deal. It's testing for the the type Impromptu with Type.GetType("ImpromptuInterface.Impromptu, ImpromptuInterface, PublicKeyToken=0b1781c923b2975b", false) which should not throw an error if it can't load it.

So you did find a bug.  At least type checking on my side could catch any extra exceptions easily enough.

**Comment by matthiesenj** [comment]
Setting the boolean to false does not suppress all exceptions of GetType it seems (including FileLoadException), but I don't understand why am I running into it in the plugin scenario and not otherwise...

**Comment by jbtule** [comment]
It's probably an environment thing, from the docs it sounds like there where things they just couldn't check in some situations. Still me catching all exceptions seems the right move.

**Comment by matthiesenj** [comment]
I tried something functionally equivalent, and it fixed the problem. I can't verify your fixed branch though, because I'm using VS2012..
