### ISSUE TITLE
.NET Core release

### ISSUE THREAD

**Issue by MiloszKrajewski** [ekonbenefits/dynamitey#18]
Hi,

Do you have any plans for .NET Core release?

Thanks,

**Comment by jbtule** [comment]
.net Standard 1.5 see PR #16, it's fully compiling but need to do more testing before it's released via nuget, but as a .net standard framework it will work with .net core.

**Comment by jbtule** [comment]
I've added to nuget Dynamitey -Version 2.0.6-beta111
this supports .net std 1.5, and works on .net core. All unit tests pass on both .net and core runtimes.
