### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by LuvForAirplanes** [ekonbenefits/dynamitey#32]
@jbtule I'm trying to use Impromptu Interface to assign an asynchronous function to an interface method:
`expando.Add("Method Name", Return<Customer>.Arguments<Customer>(async (it) => await MyAsyncMethod(prop.Name, it)));`

Unfortunately, Dynamitey does not support asynchronous assignments. Is this something that would be fairly easy to add?

Thanks in advance.

**Comment by LuvForAirplanes** [comment]
https://github.com/ekonbenefits/dynamitey/blob/master/Dynamitey/InlineLambdas.cs#L33
I hate to suggest this, but here's a really simple thought: could this line be changed to read `public static Func<Task<TR>> Arguments(Func<Task<TR>> del)`

**Comment by jbtule** [comment]
Does this not work? 
```csharp
Return<Task<Customer>>.Arguments<Customer>(async (it) => await MyAsyncMethod(prop.Name, it))
```

**Comment by LuvForAirplanes** [comment]
@jbtule I'm sorry. I'll attribute that to a brain lapse. Thanks!
