### ISSUE TITLE
InvokeGet/InvokeSet fails on private properties on Mono

### ISSUE THREAD

**Issue by PiotrZierhoffer** [ekonbenefits/dynamitey#5]
```
namespace Test1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Dynamic.InvokeSet(new ToTest(), "field", 5));
        }       
    }

    class ToTest
    {
        private int field { get; set; }
    }
}
```

Fails with Microsoft.Csharp.RuntimeBinder.RuntimeBinderException: Test1.ToTest does not contain a definition for 'field'.

Works on .NET.

Do you think it's a Mono bug or a Dynamitey issue? If it's on Mono side I'll try to extract some code and make a ticket on their bugzilla.

**Comment by jbtule** [comment]
I've been able to remove a lot of mono hacks in the latest beta nuget release. Mono has improved a lot in regards to dynamic.
