### ISSUE TITLE
Get.TryInvokeMember() throws RuntimeBinderException

### ISSUE THREAD

**Issue by franklin-ross** [ekonbenefits/dynamitey#8]
Hey,

Not sure whether this is an error, but I would expect this to return `false` if I asked it to call a method which didn't exist.

``` C#
var anon = new { a = 0 };
var get = new Get(anon);
Assert.False(() => get.TryInvokeMember(binder, args, out result));
```

Where `binder.Name == "NoMethodHere"`.

I had thought it was the job of the specific language runtime to take an appropriate action (like throw an exception) if asking a `DynamicObject` to do something it doesn't support. Is that not the case?

Cheers,
Frank.

**Comment by sjoerd222888** [comment]
Is this library still under development or is it a dead project? This bug has been opened in 2014 and now in early 2016 nothings seems to be done about it.
